# Generated by Django 4.0.3 on 2022-04-13 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0002_remove_action_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='user',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='action',
            name='task',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='action',
            name='timestamp',
            field=models.DateTimeField(default=None, null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='action',
            name='updated',
            field=models.DateTimeField(default=None, null=True, verbose_name='Update Date'),
        ),
    ]
