# Generated by Django 4.0.3 on 2022-04-13 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_remove_device_image_device_img_alter_device_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0003_action_user_alter_action_task_alter_action_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='device',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='host.device'),
        ),
        migrations.RemoveField(
            model_name='action',
            name='user',
        ),
        migrations.AddField(
            model_name='action',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
