# Generated by Django 4.0.4 on 2022-04-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_action_device_remove_action_user_action_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='data',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
