# Generated by Django 4.0.3 on 2022-04-13 05:50

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_data_profile_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/images/prof.png', upload_to=accounts.models.user_directory_path),
        ),
    ]
