# Generated by Django 4.0.3 on 2022-04-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.FileField(blank=True, upload_to='static/images/'),
        ),
    ]
