# Generated by Django 4.0.3 on 2022-04-13 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('host', '0002_alter_device_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='data',
            field=models.CharField(max_length=500000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='dateExpires',
            field=models.DateTimeField(default=None, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='device',
            name='dateManufactured',
            field=models.DateTimeField(default=None, null=True, verbose_name='date published'),
        ),
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
